### ISSUE TITLE
What if CONDA is already installed but not from Homebrew

### ISSUE THREAD

**Issue by CeKMTL** [storizzi/Deep-Live-Cam-Mac-Installer#1]
Hi, thanks for your time and effort you put into creating and sharing this work! :)

I was just wondering, before looking into the script and hacking away, if there's a specific need for conda to be installed from brew...

(base) ➜  Deep-Live-Cam-Mac-Installer git:(main) ./deep_live_cam.sh                                                                                                                                                                               
Apple Silicon (arm64) detected.
Homebrew is already installed.
Homebrew Conda not found at /opt/homebrew/Caskroom/miniconda/base/bin. Please ensure Miniconda is installed via Homebrew.
(base) ➜  Deep-Live-Cam-Mac-Installer git:(main) conda --version                                                                                                                                                                                  
conda 24.4.0

For M1 & M3

Thank you!

**Comment by CeKMTL** [comment]
I'm replying to myself:
I just put the path where my conda install is and the script worked and even asked for camera perms which I accepted. The UI launched and I can manage to make it work with camera but it is using only cpu and ultra slow... like 1 frame every 15 seconds.
Script does this at least 3 times:
Using cached onnxruntime_silicon-1.16.3-cp310-cp310-macosx_14_0_arm64.whl (7.0 MB)
Installing collected packages: onnxruntime-silicon
  Attempting uninstall: onnxruntime-silicon
    Found existing installation: onnxruntime-silicon 1.13.1
    Uninstalling onnxruntime-silicon-1.13.1:
      Successfully uninstalled onnxruntime-silicon-1.13.1
Successfully installed onnxruntime-silicon-1.16.3

**Comment by storizzi** [comment]
Hi @CeKMTL - Can you test this again - hopefully it will now use an existing conda install if it already exists without trying to install the homebrew version

**Comment by storizzi** [comment]
Assume fixed as no further reports of this issue.
