### ISSUE TITLE
Conda does not auto install

### ISSUE THREAD

**Issue by GithubOllie** [storizzi/Deep-Live-Cam-Mac-Installer#2]
Conda does not auto install. 

```
~/code/Deep-Live-Cam-Mac-Installer [main ≡]> ./deep_live_cam.sh
Apple Silicon (arm64) detected.
Homebrew is already installed.
Homebrew Conda not found at /opt/homebrew/Caskroom/miniconda/base/bin. Please ensure Miniconda is installed via Homebrew.
```

**Comment by tech-andgar** [comment]
@GithubOllie 

1. Install homebrew
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
2. Install Miniconda
`brew install --cask miniconda`

**Comment by zboyles** [comment]
After you install with @tech-andgar instructions, you'll probably need to run `conda init --all` before it lets you activate an environment.

```sh
conda init --all
conda create -n deep-live-cam python=3.10 -y
conda activate deep-live-cam
```

**Comment by storizzi** [comment]
Hi @GithubOllie - Thanks for reporting this issue - This should now be fixed. Let me know if this now works for you.

**Comment by storizzi** [comment]
Assuming fixed as no further reports of issues on this.
