### ISSUE TITLE
Blank Preview Screen After Pressing Live

### ISSUE THREAD

**Issue by brandoncamerer** [storizzi/Deep-Live-Cam-Mac-Installer#5]
Blank Preview Screen After Pressing Live,

M2 Max Chip

**Comment by brandoncamerer** [comment]
Oh... uh... nevermind.... it automatically connected to my iphone camera.... which was in my pocket... lol

**Comment by brandoncamerer** [comment]
Thanks for this by the way

**Comment by storizzi** [comment]
😃 By far my favourite Issue so far! Thanks!
